### ISSUE TITLE
envStartDev fails due to not mapping ports correctly

### ISSUE THREAD

**Issue by BrianSetz** [rug-ds-lab/sbt-scala-parent#30]
For example, using library/consul image:

```docker run -d --network=rugds-dev -p 8300:8300 -p 8301:8301 -p 8301:8301 -p 8302:8302 -p 8302:8302 -p 8400:8400 -p 8500:8500 -p 8600:8600 -p 8600:8600 --name consul library/consul:0.7.0```

Port 8600 is mapped twice. 

This is due to ExposedPorts distinguishing between TCP and UDP

```json
 "ExposedPorts": {
                "8300/tcp": {},
                "8301/tcp": {},
                "8301/udp": {},
                "8302/tcp": {},
                "8302/udp": {},
                "8400/tcp": {},
                "8500/tcp": {},
                "8600/tcp": {},
                "8600/udp": {}
            }
```

**Comment by lazovik** [comment]
What is an expected behavior then? Mapping port just once, I'd guess?

**Comment by BrianSetz** [comment]
Or, when mapping specify the protocol? 

```-p 8600:8600/udp -p 8600:8600/tcp``` ?
